ULFM_PREFIX=${HOME}/ompi/FTMPI3/RTS-ULFM/run/bin/
CC=${ULFM_PREFIX}mpicc
FC=${ULFM_PREFIX}mpif90
CFLAGS+=-g -O0

all: bindings err_returns err_returnsf err_handler err_any revoke revshrink revshrinkkill revshrinkkillrecover iagree


